### PR TITLE
Sem-Ver: api-break Re-use verifiers in the various middlewares and add an optional verifier argument to the _process_asap_token method.

### PR DESCRIPTION
**Pull request by dbaxa**
Signed-off-by: David Black <dblack@atlassian.com>

### CODE REVIEW

**Comment by mbertrand80** [comment]
Also, this caching doesn't help in practice. Many python based server applications recycle their workers every _n_ requests. This means we're still going to the keyserver way more often than is necessary or practical to get a public key. With this change, all of the internal applications that rely on this package will still have to apply the same custom hacks to get stable caching, retry, and fallback.

**Comment by mbertrand80** [comment]
I have a private implementation of the `MultiRepoPublicKeyRetriever` and `HTTPSPublicKeyRetriever` that provides session caching, utilizes Django's caching (if available), and fallback to any number of keystores provided. I can try to get that put into a Pull request soon.

**Comment by dbaxa** [comment]
@atl-gmathews I am not overly happy with the design of `Backend`, I prefer to treat my class instances as being more immutable - so I would change the various `Backend` to support being given settings but would not allow providing specific settings in the `get_verifier` method. This would then allow for `get_verifier` to return/use a cached verifier.

**Comment by erikvanzijst** [comment]
> This caching doesn't help in practice. Many python based server applications recycle their workers every _n_ requests. This means we're still going to the keyserver way more often than is necessary or practical to get a public key.

I don't think it's as bad as is sounds TBH. Yes, a cold worker process will incur a key download the first time, but:

* Not all Python services use the one process per request model (hostedstorage doesn't, PRLinks doesn't)
* The current key server's cache control expiry is only 5 minutes and so even long-lived processes have to re-download the keys more than I would have assumed

**Comment by erikvanzijst** [comment]
FWIW I took yet another approach that is lower down than the decorators or middlewares and changes the actual HTTPSPubliKeyRetriever's use of requests sessions: https://github.com/atlassian/asap-authentication-python/pull/98

**Comment by erikvanzijst** [comment]
> * The current key server's cache control expiry is only 5 minutes and so even long-lived processes have to re-download the keys more than I would have assumed

Note that the key server seems to have been aware of this issue and turned to the use of a non-standardized cache-control directive (`stale-while-revalidate`) to try and trigger asynchronous, background re-fetched.

However, the fact that this directive was never actually adopted in any published RFC means that it doesn't actually work for us: https://github.com/ionrock/cachecontrol/issues/204

**Pull request merged**
